version: '2.0'
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - '8080:8080'
#        volumes:
#            - '.:/var/www/html'
#            - /var/www/html/vendor
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: laravel
            APP_ENV: development
            APP_KEY: 'base64:9Dxc6fGW2BBuu/z0PLs5z+14vmmhfO1wB3JRGZXjtTg='
            APP_DEBUG: 'true'
            LOG_CHANNEL: stderr
    db:
        image: 'mysql:5.7'
        volumes:
            - './db:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_DATABASE: laravel

