<?php

namespace Tests;

use App\Models\User;
use App\Models\UserDetails;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    use RefreshDatabase;
    use WithFaker;
    protected $token;
    protected $testId;

    protected $token2;
    protected $testId2;

    protected $token3;
    protected $testId3;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url]);
        $userDetails = factory(UserDetails::class)->create([
            'type'=>3,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

//  User with type 2 to app devices
        $user2 = factory(User::class)->create([
            'email' => 'app@test.com',
            'password' => bcrypt('123456')]
        );
        $this->testId2 = $user2->id;
        $user2->image()->create(['url' => $this->faker->url]);
        $userDetails2 = factory(UserDetails::class)->create([
            'type'=>2,
            'user_id' => $user2->id,
        ]);
        $response2 = $this->post('api/login', [
            'email' => 'app@test.com',
            'password' => '123456',
        ]);
    
        $this->token2 = $response2->json('access_token');
        
 //  User with type 3 to  CMS
        $user3 = factory(User::class)->create([
            'email' => 'cms@test.com',
            'password' => bcrypt('123456')]
        );
        $this->testId3 = $user3->id;
        $user3->image()->create(['url' => $this->faker->url]);
        $userDetails3 = factory(UserDetails::class)->create([
            'type'=>3,
            'user_id' => $user3->id,
        ]);
        $response3 = $this->post('api/login', [
            'email' => 'cms@test.com',
            'password' => '123456',
        ]);

        $this->token3 = $response3->json('access_token');
    }
}
