<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class ApiRequest extends FormRequest
{
    protected function failedValidation(Validator $validator) :void
    {
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
        $json = response()->json(['errors'=>$validator->errors(),422]);
        throw new HttpResponseException($json);
    }
}
