<?php 

namespace Test\Unit;

use Tests\TestCase;

use App\Models\User;
use App\Models\UserDetails;
use App\Models\Posts;
use App\Models\Comments;

class CommentsControllerTest extends TestCase
{
    protected $token;
    protected $postId;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
         $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->userId = $user->id;

        $userDetails = factory(UserDetails::class)->create([
            'type' => 1,
            'user_id' => $user->id,
        ]);

        $post = factory(Posts::class)->create([
            'user_id' => $user->id,
        ]);

        $this->postId = $post->id;

        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

    }

    public function test_created_comments_201()
    {
        $response = $this->json('POST',
            'api/t/blog/posts/'. $this->postId. '/comments'.'?token=' . $this->token, 
            [
                'body' =>  $this->faker->paragraph()
            ]);

        $response->assertStatus(201);
    }

    public function test_delete_comments_200()
    {   
        $comment = factory(Comments::class)->create(['post_id' => $this->postId]);
       
        $response = $this->json('DELETE', 'api/t/blog/posts/'. $this->postId. '/comments/'.$comment->id. '/delete' .'?token=' . $this->token);
        $response->assertStatus(200);
    }

    public function test_list_comments_200()
    {
        $comment = factory(Comments::class, 60)->create(['post_id' => $this->postId]);
        $response = $this->json('GET', 'api/t/blog/posts/'. $this->postId. '/comments'.'?token=' .$this->token);

        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => [
            'id',
            'body',
            'time_ago',
            'name'
        ]]);
 
    }
}
