<?php

namespace Tests\Feature;

use App\Models\User;
use App\Models\UserDetails;
use App\Models\Admin;
use Tests\TestCase;


class FeatureListingAppTest extends TestCase
{
    protected $token;
    protected $tokenAdmin;
    protected $testId;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
         $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
      
        $user->image()->create(['url' => $this->faker->url,'name'=>'test']);
      
        $userDetails = factory(UserDetails::class)->create([
            'type' => 2,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);
    
        $this->token = $response->json('access_token');

      
    }


    public function test_create_marketplace_feature_listing_201()
    {
        $data = [
            'business_name' => 'Random',
            'email' => 'randon@test.com'
        ];

        $response = $this->json('POST',
            'api/a/marketplace-featured-listing/create?token=' . $this->token,
            $data);

        $response->assertStatus(201);
    }

}
