<?php

namespace Tests\Feature;

use App\Models\Credits;
use App\Models\Educations;
use App\Models\Performers;
use App\Models\User;
use App\Models\UserAparence;
use App\Models\UserDetails;
use App\Models\UserUnionMembers;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PerformersDatabaseControllerTest extends TestCase
{
    protected $token;
    protected $testId;



    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url,'name'=>'test']);
        $userDetails = factory(UserDetails::class)->create([
            'type'=>1,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

    }

    public function test_add_performer(){
        $director = factory(User::class)->create();
        $user = factory(User::class)->create();
        $director2 = factory(User::class)->create();
        $performer = factory(Performers::class)->create([
            'performer_id' => $user->id,
            'director_id' => $director->id,
            'uuid' => $this->faker->uuid,
        ]);
        $response = $this->post('api/t/performers/add?token='.$this->token,[
                'code'=>$performer->uuid,
                'director'=>$director2->id
            ]);

        $response->assertStatus(200);
        $response->assertJson(['data' => 'Add User OK']);
    }

    public function test_user_exits(){
        $director = factory(User::class)->create();
        $user = factory(User::class)->create();
        $performer = factory(Performers::class)->create([
            'performer_id' => $user->id,
            'director_id' => $this->testId,
            'uuid' => $this->faker->uuid,
        ]);
        $response = $this->post('api/t/performers/add?token='.$this->token,[
            'code'=>$performer->uuid,
            'director'=>$this->testId
        ]);

        $response->assertStatus(200);
        $response->assertJson(['data' => 'This user exits in your data base']);
    }

    public function test_send_code(){
        $director = factory(User::class)->create();
        factory(UserDetails::class)->create([
            'user_id'=>$director->id,
            'type'=>1
        ]);
        $sharedDirector = factory(User::class)->create(['email'=>'alphyon21@gmail.com']);
        factory(UserDetails::class)->create([
            'user_id'=>$sharedDirector->id,
            'type'=>1
        ]);
        $user = factory(User::class)->create();
        factory(UserDetails::class)->create([
            'user_id'=>$user->id,
            'type'=>2
        ]);
        $performer = factory(Performers::class)->create([
            'performer_id' => $user->id,
            'director_id' => $director->id,
            'uuid' => $this->faker->uuid,
        ]);
        $response = $this->post('api/t/performers/code?token='.$this->token,[
            'code'=>$performer->uuid,
            'email'=>$sharedDirector->email
        ]);

        $response->assertStatus(200);
        $response->assertJson(['data' => 'Code share']);
    }

    public function test_list_user_by_director(){
        $users = factory(User::class,15)->create();

        $users->each(function ($item){
            $item->image()->create(['type'=>'cover','url'=>$this->faker->imageUrl(),'name'=>$this->faker->word()]);
            factory(\App\Models\UserDetails::class)->create([
                'user_id'=>$item->id,
                'type'=>2
            ]);
            factory(Educations::class,3)->create(['user_id'=>$item->id]);
            factory(Credits::class,4)->create(['user_id'=>$item->id]);
            factory(UserAparence::class)->create(['user_id'=>$item->id]);
            factory(Performers::class)->create([
                'performer_id' => $item->id,
                'director_id' => $this->testId,
                'uuid' => $this->faker->uuid,
            ]);

        });

        $response = $this->get('api/t/performers/list?token='.$this->token);

        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => [[
            'image',
            'details',
            'appearance',
            'education',
            'credits',
            'calendar',
        ]]]);

    }

    public function test_talent_filter(){
        $users = factory(User::class,15)->create();

        $users->each(function ($item){
            $item->image()->create(['type'=>'cover','url'=>$this->faker->imageUrl(),'name'=>$this->faker->word()]);
            factory(\App\Models\UserDetails::class)->create([
                'user_id'=>$item->id,
                'type'=>2
            ]);
            factory(Educations::class,3)->create(['user_id'=>$item->id]);
            factory(Credits::class,4)->create(['user_id'=>$item->id]);
            factory(UserAparence::class)->create(['user_id'=>$item->id]);
            factory(Performers::class)->create([
                'performer_id' => $item->id,
                'director_id' => $this->testId,
                'uuid' => $this->faker->uuid,
            ]);

        });

        $response = $this->post('api/t/performers/filter?token='.$this->token,[
            'base'=>'e'
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => [[
            'image',
            'details',
            'appearance',
            'education',
            'credits',
            'calendar',
        ]]]);
    }
    public function test_talent_filter_union(){
        $users = factory(User::class,15)->create();
        $users->each(function ($item){
            $item->image()->create(['type'=>'cover','url'=>$this->faker->imageUrl(),'name'=>$this->faker->word()]);
            factory(\App\Models\UserDetails::class)->create([
                'user_id'=>$item->id,
                'type'=>2
            ]);
            factory(Educations::class,3)->create(['user_id'=>$item->id]);
            factory(Credits::class,4)->create(['user_id'=>$item->id]);
            factory(UserAparence::class)->create(['user_id'=>$item->id]);
            factory(UserUnionMembers::class)->create(['user_id'=>$item->id]);
            factory(Performers::class)->create([
                'performer_id' => $item->id,
                'director_id' => $this->testId,
                'uuid' => $this->faker->uuid,
            ]);

        });

        $response = $this->post('api/t/performers/filter?token='.$this->token,[
            'base'=>'e',
            'union'=>1
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => [[
            'image',
            'details',
            'appearance',
            'education',
            'credits',
            'calendar',
            'unions',

        ]]]);
    }

    public function test_talent_filter_non_union(){
        $users = factory(User::class,15)->create();
        $users->each(function ($item){
            $item->image()->create(['type'=>'cover','url'=>$this->faker->imageUrl(),'name'=>$this->faker->word()]);
            factory(\App\Models\UserDetails::class)->create([
                'user_id'=>$item->id,
                'type'=>2
            ]);
            factory(Educations::class,3)->create(['user_id'=>$item->id]);
            factory(Credits::class,4)->create(['user_id'=>$item->id]);
            factory(UserAparence::class)->create(['user_id'=>$item->id]);
          //  factory(UserUnionMembers::class)->create(['user_id'=>$item->id]);
            factory(Performers::class)->create([
                'performer_id' => $item->id,
                'director_id' => $this->testId,
                'uuid' => $this->faker->uuid,
            ]);

        });

        $response = $this->post('api/t/performers/filter?token='.$this->token,[
            'base'=>'e',
            'union'=>0
        ]);

        $response->assertStatus(200);
        $response->assertJsonStructure(['data' => [[
            'image',
            'details',
            'appearance',
            'education',
            'credits',
            'calendar',
            'unions',

        ]]]);
    }

}
