<?php

namespace Tests\Unit;

use App\Models\Recommendations;
use App\Models\User;
use App\Models\UserDetails;

use App\Models\Marketplace;
use App\Models\Auditions;

use Tests\TestCase;


class RecommendationsControllerTest extends TestCase
{
    protected $token;
    protected $testId;

    protected $marketplace_id;
    protected $user_id;
    protected $audition_id;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url,'name'=>'test']);
        $userDetails = factory(UserDetails::class)->create([
            'type' => 1,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);
        $marketplace = factory(Marketplace::class)->create();
        $this->marketplace_id = $marketplace->id;

        $user2 = factory(User::class)->create();
        $this->user_id = $user2->id;

        $audition = factory(Auditions::class)->create();
        $this->audition_id = $audition->id;

        $this->token = $response->json('access_token');

    }

    
    public function testCreateRecommendationsMarketplaces201()
    {
        $data = [
            'marketplace_id' => $this->faker->numberBetween(1,2),
            'user_id' => $this->faker->numberBetween(1,2),
            'audition_id' => $this->faker->numberBetween(1,2),
        ];

        $response = $this->json('POST',
            'api/t/auditions/feeback/recommendations-marketplaces?token=' . $this->token,
            $data);
        
        $response->assertStatus(201);
    }

}
