<?php
namespace Tests\Unit\Cms;

use App\Models\TypeProduct;
use Tests\TestCase;

use App\Models\User;
use App\Models\Topics;
use App\Models\UserDetails;

class TopicsControllerUnitTest extends TestCase
{

    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url,'name'=>$this->faker->word()]);
        $userDetails = factory(UserDetails::class)->create([
            'type'=>1,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

    }

    public function testListTopicsToTablet200()
    {
  
        $topic = factory(Topics::class,15)->create();

        $response = $this->json('GET',
            'api/t/topics?token=' . $this->token);
        
        $response->assertStatus(200);
    }

    public function testListTopicsToApp200()
    {
  
        $topic = factory(Topics::class,15)->create();

        $response = $this->json('GET',
            'api/t/topics?token=' . $this->token);
        
        $response->assertStatus(200);
    }

}

