<?php

namespace Tests\Unit;

use App\Models\User;
use App\Models\UserDetails;
use App\Models\UserManager;
use Tests\TestCase;

class UserManagerControllerTest extends TestCase
{
    protected $token;
    protected $testId;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url,'name'=>'test']);
        $userDetails = factory(UserDetails::class)->create([
            'type' => 2,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

    }



    public function test_manager_by_user_200()
    {
        factory(UserManager::class)->create(['user_id'=>$this->testId]);

        $response = $this->json('GET', 'api/a/managers/byuser?token=' . $this->token);

        $response->assertStatus(200);

        $response->assertJsonStructure(['data' => [
            'id',
            'name',
            'company',
            'type',
            'notifications',
            'email'
        ]]);
    }

    public function test_add_manager_user_200()
    {
        $response = $this->json('POST','api/a/managers?token=' . $this->token,[
            'name'=>            $this->faker->name(),
            'company'=>         $this->faker->company(),
            'type'=>            $this->faker->numberBetween(1,2),
            'notifications'=>   $this->faker->boolean(),
            'email'=>           $this->faker->safeEmail()
        ]);
        $response->assertStatus(201);

    }

    public function test_update_manager_user_200()
    {
        $manager = factory(UserManager::class)->create([
            'user_id' => $this->testId,

        ]);
        $response = $this->json('PUT','api/a/managers/update/'.$manager->id.'?token='. $this->token,[
            'name'=>            $this->faker->name(),
            'company'=>         $this->faker->company(),
            'type'=>            $this->faker->numberBetween(1,2),
            'notifications'=>   $this->faker->boolean(),
            'email'=>           $this->faker->safeEmail()
        ]);
        $response->assertStatus(200);

    }


}
