<?php

namespace Tests\Feature;

use App\Models\Auditions;
use App\Models\User;
use App\Models\UserDetails;
use App\Models\Admin;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class AuditionFlagCmsTest extends TestCase
{
    protected $user;
    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(Admin::class)->create([
                'email' => 'cms@test.com',
                'name' => 'Test',
                'password' => bcrypt('123456')]
        );
        $response = $this->post('api/admin/login', [
            'email' => 'cms@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('token'); 
    }

    public function test_update_banned_status()
    {
        $user = factory(User::class)->create();
        $audition = factory(Auditions::class)->create(['user_id' => $user->id]);
        $data = ['banned' => 'yes'];
        $response = $this->json('PUT',
            'api/cms/auditions/banaudition/'.$audition->id.'?token='. $this->token, $data);
        $response->assertStatus(200);
    }
}
