<?php

namespace Tests\Unit\Cms\Marketplace;

use App\Models\MarketplaceCategory;
use App\Models\Marketplace;
use Tests\TestCase;
use App\Http\Repositories\Marketplace\MarketplaceRepository;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Admin;


class MarketplaceControllerUnitTest extends TestCase
{
    use WithFaker;
    use RefreshDatabase;
    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(Admin::class)->create([
            'email' => 'cms@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;

        $response = $this->post('api/admin/login', [
            'email' => 'cms@test.com',
            'password' => '123456',
        ]);

    $this->token = $response->json('token');
    }

    public function test_create_marketplace_201()
    {
        $marketplace_category = factory(MarketplaceCategory::class)->create();

        $data = [
            'address' => 'sdsdsdsdsd',
            'title' => 'sdsdsdsd',
            'featured'=>false,
            'phone_number' => '343434343434',
            'email' => $this->faker->safeEmail(),
            'services' => 'wwewewewewe',
            'image_name' =>  'Some',
            'image_url'=>  'https://stackoverflow.com/questions/30878105/laravel-5-form-request-validation-returning-forbidden-error',
            'url_web' => $this->faker->url
        ];

        $response = $this->json('POST',
            'api/cms/marketplace_categories/'. $marketplace_category->id.'/marketplaces/create?token=' . $this->token,
            $data);

        $response->assertStatus(201);
    }

    public function test_create_marketplace_422()
    {
        $response = $this->json('POST',
            'api/cms/marketplace_categories/create?token=' . $this->token,
            []);
        $response->assertStatus(422);

    }

    public function test_show_marketplace_200()
    {
        $marketplaceCategory = factory(Marketplace::class)->create();

        $response = $this->json('GET',
        'api/cms/marketplaces/show/' . $marketplaceCategory->id . '?token=' . $this->token);
        $response->assertStatus(200);
    }

    public function test_show_all_marketplace_200()
    {
        $marketplaceCategory = factory(Marketplace::class, 10)->create();

        $response = $this->json('GET',
            'api/cms/marketplaces?token=' . $this->token);
        $response->assertStatus(200);
    }


}
