<?php

namespace Tests\Unit;

use App\Models\Auditions;
use App\Models\Roles;
use App\Models\Skills;
use App\Models\User;
use App\Models\UserDetails;
use Tests\TestCase;

class AuditionManagementTest extends TestCase
{
    protected $userId;
    protected $auditionId;
    protected $rolId;
    protected $token;

    public function test_save_upcoming_audition()
    {

        $response = $this->json('POST',
            'api/a/auditions?token='.$this->token,
            [
            'auditions' => $this->auditionId,
            'rol'=> $this->rolId,
            'type' => 1
            ]);
        $response->assertStatus(201);
        $response->assertJsonStructure(['data']);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url]);
        $userDetails = factory(UserDetails::class)->create([
            'type'=>2,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');

        $audition = factory(Auditions::class)->create([
            'user_id' => $user->id
        ]);
        $rol = factory(Roles::class)->create([
            'auditions_id' => $audition->id
        ]);
        $this->rolId = $rol->id;
        $this->userId = $user->id;
        $this->auditionId = $audition->id;
    }


}
