<?php

namespace Tests\Unit;

use App\Models\ContentSetting;
use App\Models\User;
use App\Models\UserDetails;
use App\Http\Repositories\ContentSettingRepository;

use Tests\TestCase;

class ContentSettingControllerTest extends TestCase
{
    protected $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create([
                'email' => 'token@test.com',
                'password' => bcrypt('123456')]
        );
        $this->testId = $user->id;
        $user->image()->create(['url' => $this->faker->url,'name'=>'test']);
        $userDetails = factory(UserDetails::class)->create([
            'type'=>2,
            'user_id' => $user->id,
        ]);
        $response = $this->post('api/login', [
            'email' => 'token@test.com',
            'password' => '123456',
        ]);

        $this->token = $response->json('access_token');
    }


    public function testContentSettingGetAll202()
    {

        $data = [
            'term_of_use' => $this->faker->randomHtml(2,3),
            'privacy_policy' => $this->faker->randomHtml(2,3),
            'app_info' => $this->faker->randomHtml(2,3),
            'contact_us' => $this->faker->randomHtml(2,3)
        ];

        $contentSettingRepo = new ContentSettingRepository(new ContentSetting());

        $contentSetting = $contentSettingRepo->create($data);

        $response = $this->json('GET',
            'api/a/content-settings'.'&token=' . $this->token
        );

        $response->assertStatus(200);
    }
}
