<?php

namespace Tests\Unit;

use App\Http\Exceptions\CreateException;
use App\Http\Exceptions\NotFoundException;
use App\Http\Exceptions\UpdateException;
use App\Http\Repositories\EducationsRepository;
use App\Models\Educations;
use App\Models\User;
use Illuminate\Database\QueryException;
use Tests\TestCase;


class EducationUnitTest extends TestCase
{
    protected $userId;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create();
        $this->userId = $user->id;
    }

    public function test_create_education()
    {
        $repo = new EducationsRepository(New Educations());
        $data = factory(Educations::class)->create(['user_id'=>$this->userId]);
        $credit = $repo->create($data->toArray());
        $this->assertInstanceOf(Educations::class, $credit);
        $this->assertEquals($data->name,$credit->name);
        $this->assertEquals($data->rol,$credit->rol);

    }
    public function test_create_education_exception()
    {
        $this->expectException(CreateException::class);
        $repo = new EducationsRepository(New Educations());
        $credit = $repo->create([]);
        $this->assertInstanceOf(Educations::class, $credit);
    }
    public function test_education_get_all(){
        factory(Educations::class, 5)->create(['user_id'=>$this->userId]);
        $education = new EducationsRepository(new Educations());
        $data = $education->all();
        $this->assertIsArray($data->toArray());
        $this->assertTrue($data->count() > 2);
    }
    public function test_show_education()
    {
        $credit = factory(Educations::class)->create(['user_id'=>$this->userId]);
        $creditRepo = new EducationsRepository(new Educations());
        $found =  $creditRepo->find($credit->id);
        $this->assertInstanceOf(Educations::class, $found);
        $this->assertEquals($found->name,$credit->name);
        $this->assertEquals($found->rol,$credit->rol);
    }

    public function test_update_education()
    {
        $credit =factory(Educations::class)->create(['user_id'=>$this->userId]);
        $data = [
            'rol' => $this->faker->word(),
            'name' => $this->faker->words(3,1),
        ];

        $educationRepo = new EducationsRepository($credit);
        $update = $educationRepo->update($data);

        $this->assertTrue($update);

    }

    public function test_delete_education()
    {
        $education = factory(Educations::class)->create(['user_id'=>$this->userId]);
        $educationRepo = new EducationsRepository($education);
        $delete = $educationRepo->delete();
        $this->assertTrue($delete);
    }

    public function test_show_education_exception()
    {
        $this->expectException(NotFoundException::class);
        $educationRepo = new EducationsRepository(new Educations());
        $educationRepo->find(28374);
    }
    public function test_update_education_exception()
    {
        $this->expectException(UpdateException::class);
        $education = factory(Educations::class)->create(['user_id'=>$this->userId]);
        $educationRepo = new EducationsRepository($education);
        $data = ['school'=>null];
        $educationRepo->update($data);
    }

    public function test_credit_delete_null()
    {
        $creditRepo = new EducationsRepository(new Educations());
        $delete = $creditRepo->delete();
        $this->assertNull($delete);

    }

    public function test_create_education_foreign_data()
    {
        $this->expectException(QueryException::class);
        $repo = new EducationsRepository(New Educations());
        $data = factory(Educations::class)->create();
        $education = $repo->create($data->toArray());


    }
}
